{% set name = "types-ipaddress" %}
{% set version = "1.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-ipaddress-{{ version }}.tar.gz
  sha256: a03df3be5935e50ba03fa843daabff539a041a28e73e0fce2c5705bee54d3841

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/ipaddress-python2-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for ipaddress
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
